---
- name: Setup AD for win0.example.com
  hosts: ad
  gather_facts: false
  vars:
    domain: "ad{{ student_id }}.d8k.io"
  tasks:
    - name: install ad
      ansible.windows.win_feature: >
        name=AD-Domain-Services
        include_management_tools=yes
        include_sub_features=yes
        state=present
      register: result

    - ansible.windows.win_hostname:
        name: ad
      register: r

    - name: reboot server
      ansible.windows.win_reboot:
        msg: "Change Hostname"
        pre_reboot_delay: 5
      when: r.changed

    - microsoft.ad.domain:
        dns_domain_name: "{{ domain }}"
        safe_mode_password: Password1!
      register: ad

    - name: reboot server
      ansible.windows.win_reboot:
        msg: "Installing AD. Rebooting..."
        pre_reboot_delay: 5
        reboot_timeout: 600
        post_reboot_delay: 420
      when: ad.changed

    - microsoft.ad.user:
        name: ad_drs
        password: domainuser1!
        upn: ad_drs@{{ domain }}
        groups:
          add:
            - Administrators
